import { useEffect, useMemo, useState } from 'react'
import type { AppLanguage, ProviderSettingsView } from '../../../shared/types'
import { useSessionStore } from '../store/sessionStore'
import { useAppStore } from '../app/useAppStore'
import { translate } from '../app/i18n'
import { Icon } from '../components/common/Icon'

export function SettingsPage():JSX.Element{
 const settings=useSessionStore(s=>s.settings),setSettings=useSessionStore(s=>s.setSettings),patchSettings=useSessionStore(s=>s.patchSettings)
 const language=useAppStore(s=>s.language),setLanguage=useAppStore(s=>s.setLanguage),previousView=useAppStore(s=>s.previousView),setView=useAppStore(s=>s.setView),toast=useAppStore(s=>s.toast),setSettingsDirty=useAppStore(s=>s.setSettingsDirty)
 const [form,setForm]=useState(settings),[newModel,setNewModel]=useState(''),[busy,setBusy]=useState(false)
 const t=(k:Parameters<typeof translate>[1]):string=>translate(language,k),dirty=useMemo(()=>JSON.stringify(form)!==JSON.stringify(settings),[form,settings])
 useEffect(()=>{setSettingsDirty(dirty);return()=>setSettingsDirty(false)},[dirty,setSettingsDirty])
 useEffect(()=>{const before=(e:BeforeUnloadEvent):void=>{if(dirty)e.preventDefault()};window.addEventListener('beforeunload',before);return()=>window.removeEventListener('beforeunload',before)},[dirty])
 const back=():void=>setView(previousView)
 const immediateLanguage=async(next:AppLanguage):Promise<void>=>{setLanguage(next);await window.api.setPreferences({language:next})}
 const immediateModel=async(model:string):Promise<void>=>{setForm(f=>({...f,providerModel:model}));const next=await window.api.setSettings({providerModel:model});setSettings(next)}
 const addModel=():void=>{const model=newModel.trim();if(!model)return;setForm(f=>({...f,providerModels:Array.from(new Set([...f.providerModels,model]))}));setNewModel('')}
 const removeModel=(model:string):void=>{if(form.providerModels.length===1){toast(t('modelRequired'),'error');return}if(form.providerModel===model){toast(t('defaultRequired'),'error');return}setForm(f=>({...f,providerModels:f.providerModels.filter(m=>m!==model)}))}
 const save=async():Promise<void>=>{setBusy(true);try{const patch:Partial<ProviderSettingsView>={...form,providerApiKey:form.providerApiKey==='••••configured'?'__keep__':form.providerApiKey};const next=await window.api.setSettings(patch);setSettings(next);setForm(next);patchSettings(next);toast(t('saved'))}catch(err){toast(`${t('saveFailed')}: ${String(err)}`,'error')}finally{setBusy(false)}}
 return <main className="content-page"><div className="window-drag-region"/><header className="page-header settings-header"><button className="icon-button" onClick={back}><Icon name="back"/></button><div><h1>{t('settings')}</h1><p>{t('settingsDescription')}</p></div></header><div className="settings-body"><section className="settings-section"><label>{t('apiKey')}<input type="password" value={form.providerApiKey} onChange={e=>setForm({...form,providerApiKey:e.target.value})} placeholder="sk-…"/></label><label>{t('baseUrl')}<input value={form.providerBaseURL} onChange={e=>setForm({...form,providerBaseURL:e.target.value})}/></label><label>{t('maxTokens')}<input type="number" min={256} max={32768} value={form.providerMaxTokens} onChange={e=>setForm({...form,providerMaxTokens:Number(e.target.value)||4096})}/></label></section><section className="settings-section"><label>{t('defaultModel')}<select value={form.providerModel} onChange={e=>void immediateModel(e.target.value)}>{form.providerModels.map(m=><option key={m}>{m}</option>)}</select></label><div className="setting-label">{t('models')}</div><div className="model-list">{form.providerModels.map(m=><div key={m}><code>{m}</code><button onClick={()=>removeModel(m)} title={t('removeModel')}><Icon name="x" size={15}/></button></div>)}</div><div className="add-model"><input value={newModel} onChange={e=>setNewModel(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')addModel()}} placeholder="model-name"/><button className="btn-ghost" onClick={addModel}>{t('addModel')}</button></div><label>{t('systemPrompt')}<textarea rows={5} value={form.providerSystem} onChange={e=>setForm({...form,providerSystem:e.target.value})}/></label></section><section className="settings-section"><label>{t('language')}<select value={language} onChange={e=>void immediateLanguage(e.target.value as AppLanguage)}><option value="zh-CN">简体中文</option><option value="en">English</option></select></label></section><div className="settings-save"><button className="btn-primary" disabled={busy||!dirty} onClick={()=>void save()}>{t('saveChanges')}</button></div></div></main>
}
